// Regenerates src/lib/types/generated/index.ts from the ts-rs output.
import { readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const dir = join(import.meta.dirname, "../src/lib/types/generated");
const names = readdirSync(dir)
  .filter((f) => f.endsWith(".ts") && f !== "index.ts")
  .map((f) => f.slice(0, -3))
  .sort();
const body = names.map((n) => `export type * from "./${n}";`).join("\n");
writeFileSync(join(dir, "index.ts"), `// Generated by scripts/types-index.mjs. Do not edit.\n${body}\n`);
console.log(`indexed ${names.length} types`);
